-- =========================================================================
-- 0002_transfers_asymmetric.sql
-- =========================================================================
-- Migration: replace the PIN+code symmetric transfer model with an
-- asymmetric receiver-initiated ECDH model (Option Q).
--
-- Rationale: phone-to-desktop is the dominant transfer direction. Desktop
-- has no camera so QR is useless for receiving; manual PIN entry on a
-- workstation keyboard is the friction point. Under Option Q the receiver
-- (desktop) generates an ephemeral ECDH key pair locally and uploads only
-- its public key. The sender (phone) fetches the public key by code,
-- encrypts via ECDH-derived AES-GCM key, and UPDATEs the row. The desktop
-- polls for ciphertext, decrypts locally with its private key, and DELETEs
-- the row (one-time-read preserved).
--
-- Security properties:
--   - Receiver's private key never leaves the device.
--   - Network attacker with the code cannot decrypt — they would need to
--     break P-256 ECDH.
--   - Supabase the company cannot decrypt — same reason. Subpoena returns
--     ciphertext + ephemeral public keys only.
--   - Replay defense: only one UPDATE can succeed per row (USING ciphertext
--     IS NULL). A second sender posting to the same code is rejected.
--
-- Per system-architect review (docs/reviews/arch-PR-option-q-asymmetric-
-- transfer.md condition 2): DROP+RECREATE inside a transaction is the
-- correct migration path because every row is ≤15-min ephemeral, no
-- persisted ciphertext, no migration cohort. Rollback is re-running 0001.
--
-- Per system-architect condition 6: replay defense is encoded in RLS, not
-- just the client. The "anon_update_attach_ciphertext" policy's USING
-- clause requires ciphertext IS NULL — a second UPDATE attempt fails at
-- the database layer.
-- =========================================================================

BEGIN;

-- Drop the old symmetric-model table (and its policies, indexes — CASCADE).
DROP TABLE IF EXISTS public.transfers CASCADE;

-- =========================================================================
-- New schema
-- =========================================================================
--   token                 — 5-digit lookup code (PRIMARY KEY).
--   receiver_public_key   — base64url(raw P-256 public key, 65 bytes).
--                           Generated by the receiver (desktop) when the
--                           session is created. Required at INSERT.
--   sender_public_key     — base64url(raw P-256 ephemeral public key).
--                           Generated by the sender (phone) per transfer.
--                           Required at UPDATE-with-ciphertext time.
--   ciphertext            — base64url(iv[12] || gcm_ciphertext). NULL until
--                           sender attaches it. NULLability is the replay-
--                           defense pivot.
--   expires_at            — Hard TTL (15 minutes from INSERT).
--   created_at            — Audit timestamp.
--
-- The token's 5 digits give ~17 bits of entropy. With the asymmetric
-- envelope, an attacker who guesses a code can at worst trigger a DoS by
-- UPDATEing the row with junk ciphertext (which the receiver will fail to
-- decrypt) — they cannot exfiltrate any clinician's data because the
-- receiver's private key never crosses the wire. Rate-limiting at the
-- Supabase / WAF layer remains a separate follow-up.
-- =========================================================================
CREATE TABLE public.transfers (
  token               TEXT PRIMARY KEY,
  receiver_public_key TEXT NOT NULL,
  sender_public_key   TEXT,
  ciphertext          TEXT,
  expires_at          TIMESTAMPTZ NOT NULL,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX transfers_expires_at_idx ON public.transfers (expires_at);

ALTER TABLE public.transfers ENABLE ROW LEVEL SECURITY;

-- =========================================================================
-- RLS policies
-- =========================================================================

-- INSERT — receiver creates a new session
--   Allowed only when: 5-digit token, receiver_public_key set, ciphertext
--   and sender_public_key both NULL (sender hasn't attached yet), expiry
--   is in the future and within a sane upper bound (defense against a
--   misconfigured client setting expires_at = 2099).
CREATE POLICY "anon_insert_receive_session" ON public.transfers
  FOR INSERT TO anon
  WITH CHECK (
        length(token) = 5
    AND token ~ '^[0-9]{5}$'
    AND receiver_public_key IS NOT NULL
    AND length(receiver_public_key) > 0
    AND ciphertext IS NULL
    AND sender_public_key IS NULL
    AND expires_at > now()
    AND expires_at < now() + interval '20 minutes'
  );

-- SELECT — both sender and receiver poll by token. Expired rows are not
--   visible (consistent with "session is dead" UX).
CREATE POLICY "anon_select_by_token" ON public.transfers
  FOR SELECT TO anon
  USING (expires_at > now());

-- UPDATE — sender attaches ciphertext + sender public key.
--   REPLAY DEFENSE: USING requires ciphertext IS NULL — only one sender
--   can claim each row. A second sender posting after the first succeeded
--   is rejected at the database layer, not just client-side.
--   WITH CHECK enforces that after the update both ciphertext and
--   sender_public_key are populated (sender can't just clear ciphertext
--   to re-open the slot for themselves).
CREATE POLICY "anon_update_attach_ciphertext" ON public.transfers
  FOR UPDATE TO anon
  USING (ciphertext IS NULL AND expires_at > now())
  WITH CHECK (
        ciphertext IS NOT NULL
    AND length(ciphertext) > 0
    AND sender_public_key IS NOT NULL
    AND length(sender_public_key) > 0
  );

-- DELETE — receiver removes the row after a successful one-time read.
--   Anyone with the token can also delete an expired row (cleanup helper).
CREATE POLICY "anon_delete_after_read" ON public.transfers
  FOR DELETE TO anon
  USING (true);

-- service_role bypasses RLS by default in Supabase. The cron cleanup job
-- (api/transfer-cleanup.ts) uses service_role and deletes rows where
-- expires_at < now() — no explicit policy required for that path.

COMMIT;

-- =========================================================================
-- Rollback path (manual): re-apply 0001_transfers_symmetric.sql
-- =========================================================================
