
export const SITEMAP_ROUTES = [
  '/',
  '/calculators',
  '/calculators/nihss',
  '/calculators/ich-score',
  '/calculators/abcd2-score',
  '/calculators/has-bled-score',
  '/calculators/rope-score',
  '/calculators/glasgow-coma-scale',
  '/calculators/heidelberg-bleeding-classification',
  '/calculators/boston-criteria-caa',
  '/calculators/evt-pathway',
  '/calculators/elan-pathway',
  '/calculators/se-pathway',
  '/calculators/migraine-pathway',
  '/calculators/gca-pathway',
  '/guide',
  '/guide/stroke-basics',
  '/guide/iv-tpa',
  '/guide/thrombectomy',
  '/guide/status-epilepticus',
  '/trials',
  '/trials/dawn-trial',
  '/trials/defuse-3-trial',
  '/trials/select2-trial'
];
